### ISSUE TITLE
[feature request] allow export instrumentationName

### ISSUE THREAD

**Issue by futurist** [hertz-contrib/obs-opentelemetry#16]
currently it's not possible to get tracerProvider from otel, like below:
```go
tracer := otel.GetTracerProvider().Tracer(instrumentationName)
```

since below is not exported:
```go
const (
	instrumentationName = "github.com/hertz-contrib/obs-opentelemetry"
)
```

**Describe alternatives you've considered**

Make `instrumentationName` be exported so can get the same tracer of hertz, then add new span into exiting hertz tracer.

**Comment by CoderPoet** [comment]
This is the tracer of the internal library, and it is recommended that the tracer of the business layer be separated from it. Consider customizing a tracer name, like:
```go
otel.GetTracerProvider().Tracer("your business tracer")
```
