### ISSUE TITLE
[trace] add strack trace info with trace

### ISSUE THREAD

**Issue by futurist** [hertz-contrib/obs-opentelemetry#18]
**Is your feature request related to a problem? Please describe.**

Cannot find option for record stack trace of span:

https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.14.0#WithStackTrace

**Describe the solution you'd like**

Want same option for: https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.14.0#WithStackTrace

**Additional context**

Want show stacktrace info in APMPlus in VolcEngine(currently always empty):

![image](https://user-images.githubusercontent.com/159167/230920111-0a6a783e-9bce-43d9-9286-62511f621143.png)

**Comment by welkeyever** [comment]
PTAL🙏 @CoderPoet

**Comment by rogerogers** [comment]
Usually, you can use logs to report stack traces [zap](https://github.com/hertz-contrib/obs-opentelemetry/tree/main/logging/zap) or [logrus](https://github.com/hertz-contrib/obs-opentelemetry/tree/main/logging/logrus)

code detail:
https://github.com/hertz-contrib/obs-opentelemetry/blob/f719a52136f0dd2dfdcc03f9396bc5c7fbfd7c59/logging/logrus/hook.go#L91

or report this by calling methods yourself. eg: 
```go
span := trace.SpanFromContext(c)
span.RecordError(errors.New("error info"), trace.WithStackTrace(true))
```

**Comment by rogerogers** [comment]
@futurist Hello, can this solve your problem?

**Comment by futurist** [comment]
@rogerogers Yes it's solved by add extra line of code, like below:
```go
span := trace.SpanFromContext(c)
span.SetStatus(codes.Error, desc)
span.RecordError(errors.New("error info"), trace.WithStackTrace(true))
```

Without `SetStatus` the `RecordError` do nothing, Ref: https://opentelemetry.io/docs/instrumentation/go/manual/#record-errors
