### ISSUE TITLE
Is there a way to close request traces export in provider?

### ISSUE THREAD

**Issue by langker** [hertz-contrib/obs-opentelemetry#30]
I read the following website to use hertz with opentelemetry:
https://www.cloudwego.io/zh/docs/hertz/tutorials/observability/open-telemetry/

when I run the demo below in my local:
https://github.com/cloudwego/hertz-examples/blob/main/opentelemetry/hertz/server/main.go

Each time I request the server, I found there will always be a error like below:
2023/11/30 10:43:58 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused"

In my case, I just need a trace_id and span_id to generate, but not care about whether request traces export in provider, so is there a way to close it?

**Comment by rogerogers** [comment]
Based on your description, I think you can use NoopExporter.

```go
package main

import (
	"context"

	"github.com/hertz-contrib/obs-opentelemetry/provider"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
)

func main() {
	traceExporter := tracetest.NewNoopExporter()

	p := provider.NewOpenTelemetryProvider(
		provider.WithSdkTracerProvider(sdktrace.NewTracerProvider(sdktrace.WithSpanProcessor(sdktrace.NewSimpleSpanProcessor(traceExporter)))),
		provider.WithEnableMetrics(false),
	)
	defer p.Shutdown(context.Background())
}
```

Just curious, if you don't care about uploading, maybe I can understand why you need a trace ID, but what is the purpose of the span ID?

**Comment by langker** [comment]
will span_id depend on uploading?

in our case, we will output the trace_id and span_id through log, there will be another program to deal the log.

Actually I am not understanding what upload does? Is it collect the data and show it, like grafana?

**Comment by li-jin-gou** [comment]
Can work with https://www.volcengine.com/docs/6431/158278
