### ISSUE TITLE
got 2 logs when use logging/zap as logger handler

### ISSUE THREAD

**Issue by karliehgf** [hertz-contrib/obs-opentelemetry#55]
**Describe the bug**
why got 2 logs when use logging/zap as logger handler, and how to create trace-id when got nil from request header?

**Expected behavior**

**Screenshots**

 my code:
 `
package main
import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hertz_zap "github.com/hertz-contrib/obs-opentelemetry/logging/zap"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	ozap "go.uber.org/zap"
)

func main() {
	hlog.SetLogger(
		hertz_zap.NewLogger(
			hertz_zap.WithTraceErrorSpanLevel(ozap.WarnLevel),
			hertz_zap.WithRecordStackTraceInSpan(true)))
	hlog.SetLevel(hlog.LevelInfo)
	tracer, cfg := hertztracing.NewServerTracer()
	h := server.Default(tracer)
	h.Use(hertztracing.ServerMiddleware(cfg))
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxInfof(c, "this is test a")
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.Spin()
}
`
 result:
 
![image](https://github.com/hertz-contrib/obs-opentelemetry/assets/8002468/38bacd75-f1d2-4252-8c06-ffcf915c4b16)

**Hertz version:**

v0.8.1

**Environment:**
GOVERSION='go1.21.8'

**Additional context**

**Comment by rogerogers** [comment]
https://github.com/hertz-contrib/obs-opentelemetry?tab=readme-ov-file#server-usage 
You need to set up the provider according to the documentation first

The two lines of logs seem to be a bug

**Comment by karliehgf** [comment]
it works well when i set up the provider.
but in my case,  i do not have an opentelemetry servir and I just want to use the logging component to logging with trace_id，can i use NewTracerProvider() instead of NewOpenTelemetryProvider() ?

**Comment by rogerogers** [comment]
Of course, you can use `trace.NewTracerProvider`, `provider.NewOpenTelemetryProvider` just provides a more convenient way
