### ISSUE TITLE
Can not output extraKey I passed in when using logging/zap

### ISSUE THREAD

**Issue by ponecrazy** [hertz-contrib/obs-opentelemetry#61]
**Describe the bug**

When using logging/zap with otel, if the span's IsValid() is false, the extraKey I passed in cannot be output in the log

**Screenshots**

![image](https://github.com/user-attachments/assets/b28bcc25-43e7-4654-9019-53f335e98cf3)

github.com/hertz-contrib/obs-opentelemetry/logging/zap/logger.go: 59

**Version**
github.com/hertz-contrib/obs-opentelemetry/logging/zap v0.0.0-20240705015228-9abdf96254a2
github.com/hertz-contrib/obs-opentelemetry/tracing v0.4.1

**Comment by GuangmingLuo** [comment]
@rogerogers please take a look

**Comment by rogerogers** [comment]
Thank you for the feedback. Update and try again.
